project_id = "smdbfaomeghoejqqkplv"

[auth]
enabled = true
site_url = "https://studiocodekenya254.qzz.io"
additional_redirect_urls = [
  "https://studiocodekenya254.qzz.io",
  "https://studiocodekenya254.qzz.io/landing_page.html",
  "https://studiocodekenya254.qzz.io/client_dashboard.html",
  "https://studiocodekenya254.qzz.io/developer_dashboard.html",
  "https://studiocodekenya254.qzz.io/sales_dashboard.html",
  "https://studiocodekenya254.qzz.io/admin_dashboard.html",
  "http://localhost:3000",
  "http://localhost:3000/landing_page.html",
  "http://127.0.0.1:3000",
  "http://127.0.0.1:3000/landing_page.html"
]

[auth.external.google]
enabled = true
client_id = "335856743456-bvgksj4s3v1ri680pbv8bp56o6kaj9gq.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
redirect_uri = ""
url = ""
skip_nonce_check = true
email_optional = false

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

[functions.send-invoice]
verify_jwt = false

[functions.initiate-topup]
verify_jwt = false

[functions.profile-write]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.send_gmail]
verify_jwt = false
