-- Safe non-destructive index hardening (idempotent)
-- Generated by deep-scan phase3to9

create index if not exists idx_projects_client_id on public.projects(client_id);
create index if not exists idx_projects_commissioner_id on public.projects(commissioner_id);
create index if not exists idx_projects_developer_id on public.projects(developer_id);
create index if not exists idx_invoices_client_email on public.invoices(client_email);
create index if not exists idx_invoices_created_by on public.invoices(created_by);
create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_financial_transactions_project_id on public.financial_transactions(project_id);
create index if not exists idx_financial_transactions_invoice_id on public.financial_transactions(invoice_id);
create unique index if not exists ux_wallet_topups_paystack_reference on public.wallet_topups(paystack_reference) where paystack_reference is not null;
